algoritmo "Valores"
// Função :
// Autor :
// Data : 25/07/2017
// Seção de Declarações 
var
   N1, N2, M: Real

inicio
      Escreval
      Escreval
      Escreva("Digite um Número: ")
      Leia (N1)
      Escreval
      Escreval
      Escreva ("Digite um Segundo Número: ")
      Leia (N2)
      M <- (N1 + N2)/2
      Escreval
      Escreval
      Escreva ("A Média entre ",N1," e ",N2," é ",M)
      Escreval
      Escreval
// Seção de Comandos 
fimalgoritmo
